# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
               users:
                  Usuario:
                      password: usuario
                      roles: 'ROLE_USER'
                  admin:
                      password: admin
                      roles: 'ROLE_ADMIN'
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
             pattern: ^/
             anonymous: ~
             http_basic:
                realm: "gallery"
    access_control:
        - { path: ^/users, roles: ROLE_ADMIN}
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext