# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
   app.brochure_uploader:
        class: AppBundle\FileUploader
        arguments: ['%image_directory%']
   app.item_form:
        class: AppBundle\Form\ItemType
   app.upload_image:
        class: AppBundle\Model\UploadImage
        arguments: [@service_container]
   app.items_listener:
        class: AppBundle\Event\ItemsListener
        arguments: [@logger]
        tags:
          - { name: monolog.logger, channel: test }
          - { name: kernel.event_listener, event: item.create, method: onItemCreate }
          - { name: kernel.event_listener, event: item.delete, method: onItemDelete }
          - { name: kernel.event_listener, event: item.update, method: onItemUpdate }